// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: messages/IssueTokens.proto

package protoobj

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueTokensRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientIp string `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
}

func (x *IssueTokensRequest) Reset() {
	*x = IssueTokensRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_IssueTokens_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokensRequest) ProtoMessage() {}

func (x *IssueTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_IssueTokens_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokensRequest.ProtoReflect.Descriptor instead.
func (*IssueTokensRequest) Descriptor() ([]byte, []int) {
	return file_messages_IssueTokens_proto_rawDescGZIP(), []int{0}
}

func (x *IssueTokensRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IssueTokensRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type IssueTokensResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken  string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
}

func (x *IssueTokensResponse) Reset() {
	*x = IssueTokensResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_IssueTokens_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokensResponse) ProtoMessage() {}

func (x *IssueTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_IssueTokens_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokensResponse.ProtoReflect.Descriptor instead.
func (*IssueTokensResponse) Descriptor() ([]byte, []int) {
	return file_messages_IssueTokens_proto_rawDescGZIP(), []int{1}
}

func (x *IssueTokensResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *IssueTokensResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_messages_IssueTokens_proto protoreflect.FileDescriptor

var file_messages_IssueTokens_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x49, 0x73, 0x73, 0x75, 0x65,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x4a, 0x0a, 0x12, 0x49, 0x73, 0x73, 0x75, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x22, 0x5d, 0x0a,
	0x13, 0x49, 0x73, 0x73, 0x75, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x12, 0x5a, 0x10,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6f, 0x62, 0x6a,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_IssueTokens_proto_rawDescOnce sync.Once
	file_messages_IssueTokens_proto_rawDescData = file_messages_IssueTokens_proto_rawDesc
)

func file_messages_IssueTokens_proto_rawDescGZIP() []byte {
	file_messages_IssueTokens_proto_rawDescOnce.Do(func() {
		file_messages_IssueTokens_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_IssueTokens_proto_rawDescData)
	})
	return file_messages_IssueTokens_proto_rawDescData
}

var file_messages_IssueTokens_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_messages_IssueTokens_proto_goTypes = []any{
	(*IssueTokensRequest)(nil),  // 0: msg.IssueTokensRequest
	(*IssueTokensResponse)(nil), // 1: msg.IssueTokensResponse
}
var file_messages_IssueTokens_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_IssueTokens_proto_init() }
func file_messages_IssueTokens_proto_init() {
	if File_messages_IssueTokens_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_IssueTokens_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*IssueTokensRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_IssueTokens_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IssueTokensResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_IssueTokens_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_IssueTokens_proto_goTypes,
		DependencyIndexes: file_messages_IssueTokens_proto_depIdxs,
		MessageInfos:      file_messages_IssueTokens_proto_msgTypes,
	}.Build()
	File_messages_IssueTokens_proto = out.File
	file_messages_IssueTokens_proto_rawDesc = nil
	file_messages_IssueTokens_proto_goTypes = nil
	file_messages_IssueTokens_proto_depIdxs = nil
}
